[shell]
program = "/opt/homebrew/bin/fish"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "MonaspiceAr Nerd Font Mono"
style = "Regular"

[font.bold]
family = "MonaspiceAr Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MonaspiceAr Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "MonaspiceAr Nerd Font Mono"
style = "Bold Italic"

